### ISSUE TITLE
"please add ShowGrowthHack activity in your manifest" error 

### ISSUE THREAD

**Issue by dhruvbansal3** [appvirality/AppVirality-Android-SDK#1]
I have done everythings mentioned at https://github.com/appvirality/appvirality-sdk-android/wiki/Personalized-In-App-Referrals but still getting "please add ShowGrowthHack activity in your manifest" error.

**Comment by papinenilaxman** [comment]
Hi Dhruv,

Can we have your email id to digg into this further? or please email me at lax@appvirality.com

**Comment by dhruvbansal3** [comment]
Hi my id is dhruvbansal3@gmail.com

I think the problem is with mafisfestmerger.enabled = true in
project.properties. it is not working .

Thanks

On Tue, May 12, 2015 at 7:17 AM, Laxman Papineni notifications@github.com
wrote:

> Hi Dhruv,
> 
> Can we have your email id to digg into this further? or please email me at
> lax@appvirality.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appvirality/AppVirality-Android-SDK/issues/1#issuecomment-101096183
> .

## 

Dhruv Bansal
Software Engineer
+91 -9716257812
_dhruvbansal3@gmail.com dhruvbansal3@gmail.com_

**Comment by RamPapineni** [comment]
That could be the problem. please make "manifestmerger.enabled=false" and move the manifest entries from "AppviralityUI" to your main project mainifest file.

**Comment by dhruvbansal3** [comment]
It worked without this change.

Another thins i want to know is step 7 - Welcome screen.

at  this link
https://github.com/appvirality/appvirality-sdk-android/wiki/Personalized-In-App-Referrals

AppviralityUI.showWelcomeScreen(MyActivity.this);

I added this line in code ,  Can you please let me know when this will get
executed and welcome screen will be shown ?

How are you tracking install from a particular referrer without
install_referrer receiver in manifest.xml  ?

Thanks and Regards
Dhruv Bansal

On Tue, May 12, 2015 at 9:44 AM, Ram notifications@github.com wrote:

> That could be the problem. please make "manifestmerger.enabled=false" and
> move the manifest entries from "AppviralityUI" to your main project
> mainifest file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appvirality/AppVirality-Android-SDK/issues/1#issuecomment-101124368
> .

## 

Dhruv Bansal
Software Engineer
+91 -9716257812
_dhruvbansal3@gmail.com dhruvbansal3@gmail.com_
