### ISSUE TITLE
User key keeps changing every time on opening Activity  and not able to get balance 

### ISSUE THREAD

**Issue by rahulpandey** [appvirality/AppVirality-Android-SDK#2]
As per doc we have added the code ie  AppviralityAPI.getInstance(getApplicationContext(), new AppviralityAPI.UserInstance() { @Override public void onInstance(AppviralityAPI instance) { }} 
but every time it always return new user key its keep changing. and we are not able to get redeem balance of user

**Comment by papinenilaxman** [comment]
Rahul, could you pls provide your email id? or reachout to ram [at] appvirality.com.

**Comment by rahulpandey** [comment]
you can reach me at pandey-rahul@hotmail.com thanks,
